### PR TITLE
Faster audio

### PR DESCRIPTION
**Pull request by xyzzy42**
I discovered that despite having a fairly fast computer, tg would not run at full speed.

So I did some profiling and looked through the code and made some changes to speed up the biggest slow points which were also easy to fix.

It's much faster after this!  I can run it at full speed with the largest processing buffer without using 100% CPU.

I have some other changes to make it faster still, but they are less interesting than these and more invasive.

### CODE REVIEW

**Comment by vacaboja** [comment]
Hi, sorry for the delay.

Thanks a lot, this looks very good! I'll do a few tests shortly, and then I will merge.

**Review by jakelewis3d — COMMENTED** [review]
Would it make sense to do the hpf, noise suppressor, and lpf  in the  port audio callback for the same reason (to prevent duplicate processing)?

**Comment by xyzzy42** [comment]
Yes, totally would make sense to do something like that.  I know I looked into this, but it's been so long I don't remember for sure, but I think the thread that PA calls the callback on is also the thread that services the audio interface (e.g., alsa).  So if you spend too long in the calback, you drop audio, which is really bad for the algorithm.

That's not an issue for this patch, since it actually makes the callback faster and less likely to drop!

It the CPU can't keep up with the non-callback part of audio processing, it just refreshes the UI at < 10 Hz and doesn't drop audio.  So putting the slower processing not in the callback thread does provide an advantage.

But it could still be done once instead of over and over, and still in another thread.  I also looked into that, and I think it wasn't slightly challenging in that the processing was not necessary the same for each run of the processing buffers.  But I've forgotten by now.

**Comment by jakelewis3d** [comment]
I've just issued a pull request that moves the high and low pass filters from algo into audio, and allows selection of sample rate at the device level.  And a GUI to control it all.

**Comment by vacaboja** [comment]
Hi!

I can merge this. Should I do it now, or is it better to wait for your other pull request?

**Comment by xyzzy42** [comment]
This PR is my only one.  The other PR is by @jakelewis3d and appears to be based on this one, but it's harder to tell:  It has just one commit with all changes squashed.  I have tried to organize this into distinct, well documented, commits that do one thing for easier review and to better allow the git history to explain what the code does.

I was also careful to test that there is no change in the algorithms and they will produce the same results as before, only faster.  I have other changes that do change the math and possibly produce different results, but did not include them here, so there would not need to be a quality vs performance trade-off to consider.

**Comment by vacaboja** [comment]
Thanks a lot! Sorry for confusing the PRs. I'm merging this one for now.

**Comment by jakelewis3d** [comment]
Sorry for the messy commit.
My concern might be that the filters are now applied in a different order:
It was   hpf, noise suppression,  fabs, lpf, averaging.
now it is hpf, fabs, lpf, noise suppression, averaging.

I'm not sure how much difference that will make though,

I don't have a wide variety of watches to test on here, just 21600 and
28800. Is there a repository of wav files of different movements -
particularly problematic ones (out of beat, noisy, etc)
Jake

**Comment by vacaboja** [comment]
Sorry Jake, I am a bit confused. With "now", do you mean in your PR, or do you mean in this one (xyzzy42's)? This one did not appear, to me, to change the order of the processing steps.

**Comment by jakelewis3d** [comment]
Sorry, I meant my PR (#19) not this one.
Jake

**Pull request merged**
