### PR TITLE
Tweaks for OSX compilation.

### PR DESCRIPTION
**Pull request by wahlstedt**
A simple test pull request for starters.

This simply renames the refresh() function in order to avoid a naming conflict with OSX.

### CODE REVIEW

**Comment by wahlstedt** [comment]
That second commit with the watch animation wasn't really supposed to be included in this pull request but I'll leave it in there in case you want to use it. :)

**Comment by vacaboja** [comment]
Hi,

thank you a lot for your contribution!

I included the fixes for OS X. After a lot of deliberation, I think that I
prefer to keep the icon as it was. There are two resons. One is that I
would like to keep the interface as minimalistic as possible, which means
for me not to include any feature which is not strictly needed to convey
information on the watch. The second is that I prefer the local time not to
show up in people's screenshots, because someone might want not to disclose
this information.

If you are interest in contributing code to this projects, there are a few
features that I believe would enance the user experience.

One, that somene requested I think, is to give to tg the ability to
screenshot itself. This should not be hard. But we can probably do better:
we can make it output directly to a nice black and white PDF ready to be
printed. Cairo, the library used to draw the interface, can output to PDF
natively, so it might be that the very same code that draws the interface
can also draw a PDF, with not many modifications besides changing the
colors.

Another is to multithread the algorithm to make it more responsive. I'm
preparing the actual threaded code, but this is a trivial busines because
OpenMP does all the work, I just have to add a couple of pragma directives
here and there and do some testing. The problem is to figure out how many
threads to use. I have got a hunch that we should use the number of
physiscal cores on the machine. Unfortunately, I don't know any
cross-platform way to get this number, so we might have to ifdef
platform-specific code. If you want to experiment with the threaded code, I
will post a branch on github as soon as I get it going (tomorrow I will
have no time to program, so it's probably next week or so).

Thanks again,
Marcello

**Comment by wahlstedt** [comment]
> I included the fixes for OS X. After a lot of deliberation, I think that I
> prefer to keep the icon as it was. 

No worries. It was mainly a result of some playing around with GTK since I’ve never used that before.

One suggestion I have is to abstract the GTK code as much as possible, to make it easier to port over to another framework like Qt or native APIs on OS X / iOS. Most of the stuff is already located in interface.c, but there are a couple of functions in there that don’t deal with the GUI.

> If you are interest in contributing code to this projects, there are a few
> features that I believe would enance the user experience.
> 
> One, that somene requested I think, is to give to tg the ability to
> screenshot itself. This should not be hard. But we can probably do better:
> we can make it output directly to a nice black and white PDF ready to be
> printed. Cairo, the library used to draw the interface, can output to PDF
> natively, so it might be that the very same code that draws the interface
> can also draw a PDF, with not many modifications besides changing the
> colors.

PDF output would be a good feature. May I suggest something along the lines of what the Witschi machines output, as seen in https://www.youtube.com/watch?v=QwUXg4YNgrY https://www.youtube.com/watch?v=QwUXg4YNgrY

This would require support for positional measurements to be stored, which is another feature worth considering. :)

This is a nice project and I applaud your efforts to make it cross-platform. I hope to be able to contribute more but I have one complaint: the code is not commented! For someone not familiar with GTK it takes an unnecessary long time to parse the code. Not to mention whatever is going on in algo.c lol ( I’m sure it’s over my head but it would be fun to have a basic understanding of what’s being done. :)

Perhaps you plan to add more comments and user documentation as the code stabilises, but would you be interested in pull requests with comments added by me? I tend to want to add them as I go through the code to help myself. Well documented projects usually makes it easier to attract more contributors as well. :) 

Another suggestion I have is to post about this project at http://www.watchrepairtalk.com http://www.watchrepairtalk.com/ It’s aimed at hobbyists and a bit more relaxed compared to Watchuseek and will probably generate some good additional feedback.

Cheers!

/Robert

**Comment by vacaboja** [comment]
On Sun, Dec 13, 2015 at 12:47 AM, Rob notifications@github.com wrote:

> One suggestion I have is to abstract the GTK code as much as possible, to
> make it easier to port over to another framework like Qt or native APIs on
> OS X / iOS. Most of the stuff is already located in interface.c, but there
> are a couple of functions in there that don’t deal with the GUI.
> 
> Yes, if you want feel free to create a new file and put there the functions
> that are not strictly GUI.

By the way, if you want to port to Qt, that is top priority. I didn't use
Qt in the first place because I have no experience with that, and this
program was originally meant for my exclusive personal use. Had I designed
tg for distribution from the beginning, I would have learnt Qt: going GTK
was a mistake. Qt has a more native feel, builtin audio (probably), and
support for android tablets and phones.

> This would require support for positional measurements to be stored, which
> is another feature worth considering. :)

Yep. This was also suggested by another WUS member (in PM).

> This is a nice project and I applaud your efforts to make it
> cross-platform. I hope to be able to contribute more but I have one
> complaint: the code is not commented! For someone not familiar with GTK it
> takes an unnecessary long time to parse the code. Not to mention whatever
> is going on in algo.c lol ( I’m sure it’s over my head but it would be fun
> to have a basic understanding of what’s being done. :)
> 
> Perhaps you plan to add more comments and user documentation as the code
> stabilises, but would you be interested in pull requests with comments
> added by me? I tend to want to add them as I go through the code to help
> myself. Well documented projects usually makes it easier to attract more
> contributors as well. :)

You guessed correctly. I postponed the documentation because the code was
not stable, and I didn't know if tg was going to get any user at all. I
definitely have to add comments to the code, and to algo.c in particular!
Your offer to add comments is very much welcome!

> Another suggestion I have is to post about this project at
> http://www.watchrepairtalk.com http://www.watchrepairtalk.com/ It’s
> aimed at hobbyists and a bit more relaxed compared to Watchuseek and will
> probably generate some good additional feedback.
> 
> Good idea! I didn't know this forum. I don't post now because I know that I
> am not going to have much time in the next week or two, but it's on the
> to-do list!

```
Marcello.
```

**Comment by wahlstedt** [comment]
> On 13 Dec 2015, at 12:02, vacaboja notifications@github.com wrote:
> 
> By the way, if you want to port to Qt, that is top priority. I didn't use
> Qt in the first place because I have no experience with that, and this
> program was originally meant for my exclusive personal use. Had I designed
> tg for distribution from the beginning, I would have learnt Qt: going GTK
> was a mistake. Qt has a more native feel, builtin audio (probably), and
> support for android tablets and phones.

I have no experience with Qt either, and agree that it looks more capable. However, GTK seems like a better option for easy cross-platform development. Qt requires C++ and extra pre-processor steps that don’t look very appealing.

The app has a pretty simple UI so GTK should be good enough and as long as the gfx functions are abstracted well enough it shouldn’t be that hard to adapt them into native version if someone wants to port them to non-GTK platforms (e.g. Android or iOS).

Any reason for not using GTK 3 though? I noticed some of the v2 functions used are deprecated. If you want I could look into updating it to GTK 3. Note that I’m a GTK newbie as well, my GUI focus lately has been with Cocoa (OSX & iOS). But GTK seems similar enough that it doesn’t look too daunting.

> Your offer to add comments is very much welcome!

I’ll be sure to include any I have added in future commits then! :)

Cheers,

/Robert

**Pull request closed without merging**
