### PR TITLE
Autotools build system

### PR DESCRIPTION
**Pull request by stefantalpalaru**
This should simplify packaging for all the supported operating systems. I made this while working on a Gentoo Linux package for "tg".

### CODE REVIEW

**Comment by vacaboja** [comment]
Hi!

Sorry for answering late. I am very happy to have the opportunity to add autotools scripts for tg. Actually, the only reason why I didn't do it myself is that I do not know how to use them.

There are a few things that I need to make the switch: could you help me with them?

1 - Actually, I was about to release the next version of tg: the code of this new version is located in the branch test of my repository. It would be great to add autotools for this new version. Changes include the switch to GTK+3 and the removal of tg-lt (the light algorithm can now be activated with a setting).

2 - I would like all the build artifacts (so every file produced by the build process) to end up in the "build" subdirectory and to have a make target "clean" that just clears that directory. Can this be achieved with autotools?

3 - I have a number of targets in my makefile to produce various version of the executable: for debugging, for profiling, for running with valgrind. Can this be replicated?

**Comment by stefantalpalaru** [comment]
Sure, I can port this to the "test" branch.

"make clean" is already provided by Autotools.

Are you OK with this workflow that already works for placing the resulting binaries in a subdir?

```
./autogen.sh
mkdir build
cd build
../configure
make
```
Yes, we can add separate make targets if you're not happy with passing the respective flags as env vars or as configure arguments (I just did that for the debugging binary).

**Comment by vacaboja** [comment]
Thanks for your quick answer. I have been at a conference until Sunday, and I could find some time for tg only this evening...

I just read something, very little, about autotools, and I understand (correct me if I am wrong) that the method that you suggest to build in a subdir is actually the standard, so I will go with it.

About adding configure options or make targets, I would be very grateful if you could. I can not really figure out which of the two options is the correct one. So, I would prefer make targets, but this might not be the right thing to do.

As far as I understand, the work of autogen.sh (and all the autoconf black magic it invokes) is influenced only by the source files (configure.ac, and also something else?). This creates the configure script, and it is the configure script that actually takes care of system-dependent settings on the target machine. If this is the case, perhaps we should check-in also the configure script (and the associated files like install-sh, compile, etc.), so one does not need autotools just to build the projects. Actually, most autotools projects that I saw actually ship with a configure script. That would also make life easier for me when I make the windows build. Is there any drawback?

**Comment by stefantalpalaru** [comment]
Most projects keep the generated files (configure, Makefile, etc.) outside of version control, but put them in the tarball you get from "make dist". The idea is that developers using git already have Autotools installed, while regular users can manage without it.

I've already implemented make targets for the alternative binaries. Now working on the mimetype related icons. I'll make a new push request against the "test" branch when I'm done.

**Comment by vacaboja** [comment]
Thanks. Let's not check in configure etc. Actually, it seems that with MSYS2 I can get autotools on windows quite easily, so, since on OS X the build has already been tested by travis, it should be ok on all platforms.

Thanks again, and I count on your next pull request!

**Comment by vacaboja** [comment]
The pull request on test has been merged, and that branch will eventually be merged into master. Would you agree to close this one?

**Comment by stefantalpalaru** [comment]
Sure.

**Pull request closed without merging**
