### PR TITLE
Audio Settings Dialog

### PR DESCRIPTION
**Pull request by jakelewis3d**
Signed-off-by: jakelewis3d <jakelewis3d@gmail.com>
Following on from the Faster audio submission by @xyzzy42,   and setting dialog by @wahlstedt.

1) I've moved the high pass and low pass filtering to the audio fill_buffers method.
Unfortunately, I couldn't get the noise_suppressor filter to work well in fill_buffers, so that is still being processed in algo, so the order of filters has changed.

2)I'm using a contact mic (piezo) so I'm not having such noise issues. To this end I've created options to use a minimal peak_detector method, and compute_waveform methods that skip the expensive averaging.  I've also added some integer arithmetic to compute_waveform and compute_period as a full 5% of profile time was spent in round()!

3) Both audio input device and sampling bit rate are now selectable from 44100 and 22050. I've also added in 32768 and 16384 as these sizes are particularly suitable for fft transforms, although I'm not sure all sound cards can support them.  The code does make a check that the sampling rate is supported prior to populating the options, but I've had false positives.  

4) Selecting 22050 makes the subsampling of Light mode redundant, so I've removed all that code.  Light mode now just reduces the size of the processing buffers.

5) I've added a GUI so these changes can be turned on and off during runtime. This is useful for testing, although I don't suggest that all this complexity is exposed to end-users - perhaps just options for sample rate and mic type ( piezo or regular).  

6) For the high and low pass filter range GUIs to reflect updates rapidly I've introduced the concept of 'freshdata'.  This reduces the lag of the having to wait for up to 16 seconds for the processing buffers to fill up with the changes to filter freq.

AudioSettingsDialog

For windows users, ( who trust me), I've a compiled version of TG with these changes for you to try, unzip the executable into your regular TG folder: [https://horologyobsession.com/downloads/timegrapher/audiosettings/AudioSettings_unzipContentsToTGfolder.zip](url)

### CODE REVIEW

**Comment by xyzzy42** [comment]
It's likely your sound hardware does not support the 16k or 32k rates and they are being created through resampling in software.  A modern Linux install will do this by default, as the default audio sampling device is the pulse audio software stack, which will resample.  It possible that the interface portaudio uses on windows does the same thing.

**Comment by jakelewis3d** [comment]
Possibly, but some of my audio inputs report that they cannot support 32 or
16k, while others reported they can, and indeed do, albeit likely thru
software downsampling.

Does the software downsampling include the appropriate low pass filter?
Jake

**Comment by xyzzy42** [comment]
Would depend on the software doing the resampling, but almost certainly it would.  Using pulseaudio on Linux does.  So do the older ALSA plugins.  I see that my microphones only support 48kHz when used directly, but if I use one of the inputs that goes through pulse, then I can use any sampling rate.  Since pulse resamples in software.

It could be your hardware allows any sample rate.  That is something that is possible.  But it is not that common anymore.  More so in the days of add-on sound cards and when resampling audio in a CPU would use a major portion of the CPU's total bandwidth.

**Comment by vacaboja** [comment]
Hi!

That's great. I was going to merge your previous pull request, but maybe should I rather do this one?

About the software downsampling in linux, pulse audio I guess, I have had strange experiences. Probably it does proper filtering, as it is designed to work with music. However the timing is unpredicatble. My guess is that, at least on some systems, it does (or did) some sort of decimation based on a fixed buffer size, so that the ratio of the sampling periods has to be approximated to an integer fraction of the length of the buffer. For this reason I don't think that relying on the internal subsampling is a good idea for timing. At the very least, calibration would have to change depending on the sampling frequency, which is odd.

I am very much a fun of doing things properly, but remember that, for our purpose, doing proper filtering before subsampling is not required, and it may even be detrimental. Indeed there is a reason why I didn't do it in the first place. So, essentially the sound of a watch is noise, and we are graphing noise level against time. Of course there is desired noise, namely that of the watch, and undesirable ambinent noise. If you omit the subsampling filter, all the noise that is above the Nyquist frequency appears reflected down in frequency, as an artifact. Still it's noise, and we are only interest in its intensity. Problem is: is that stuff mostly good noise (watch) or bad noise (ambient, electrical, whatever)? In my experience it is mostly good, ad most ambient noise tends to be in the lower parts of the spectrum. Did some testing, and I didn't notice any benefit in filtering, still I'm open to comments.

**Comment by xyzzy42** [comment]
I am not sure the details of the pulse audio resampling.  But I remember the older ALSA plugin based system, this was a problem.  We have as a source sound hardware producing a constant integer number of samples per period.  And we want to appear as if we are sound hardware producing a constant integer number of samples per period after the resampling plugin.  But the sampling rates are not an integer ratio.  We can not produce periods with 30105.6 samples!  It would produce periods with an extra sample to solve this.  This would effect timing!  1 sample in a 32kiS buffer @48kHz would be 2.6 s/d.

I am sure that adding the delay through the pulseaudio pipeline does not help.

To get best performance on Linux:

1. Support multiple sampling rates in the code, instead of fixed compile time selection of 44.1 kHz.
2. Use the "direct" audio input for the microphone and bypass pulse audio.  This means one must use a supported native rate of the microphone or soundcard, e.g. 48 kHz.  This is why you need 1, above, to get this to work usefully.  This will avoid variable delay from pulse audio pipeline.  Also avoid the unnecessary CPU spent on software resampling.  And software volume and mixing.
3. Do not request a specific period buffer size from port audio.  Otherwise it will re-pack the audio into periods of the requested size and there will be a partial period of audio of variable size left over, adding a non-constant delay.
4. Use the timestamp portaudio provides with each buffer.  This comes from ALSA and is an accurate timestamp of the audio period's sample time.  This should have *very good* absolute accuracy in anything using NTP, which is the default for Linux distros for years now.

I had not thought of the lack of lpf before resampling in the way you put it, but it very much makes sense.  Most of the energy of the click is in the higher frequencies.  To filter it out will be a detriment.    Better to alias it so that the energy is still there.  Yes, some of the click noise will be aliased into other parts of the click noise, but this is fine.  We do not analyse the spectrum of the click so this does not matter.

If anything, it might make sense to run a HPF before resampling.  So that it can remove ambient noise before resampling aliases some of the high frequency click noise into that part of the spectrum.

**Comment by jakelewis3d** [comment]
1. *Support multiple sampling rates in the code, instead of fixed
   compile time selection of 44.1 kHz.*
   This has been mostly implemented in this PR 19. It would be
   straightforward to allow user input to the combo box.

   2. *Use the "direct" audio input for the microphone and bypass pulse
   audio. This means one must use a supported native rate of the microphone or
   soundcard, e.g. 48 kHz. This is why you need 1, above, to get this to work
   usefully. This will avoid variable delay from pulse audio pipeline. Also
   avoid the unnecessary CPU spent on software resampling. And software volume
   and mixing.*

   I thought 44.1 was the native rate, but I'm not an audio guy. Is that
   48000hz or 48*1024.


   3. *Do not request a specific period buffer size from port audio.
   Otherwise it will re-pack the audio into periods of the requested size and
   there will be a partial period of audio of variable size left over, adding
   a non-constant delay.*
   I don't think we are - isn't that what the paFramesPerBufferUnspecified
   parameter is in the call to Pa_OpenStream()

   4. *Use the timestamp portaudio provides with each buffer. This comes
   from ALSA and is an accurate timestamp of the audio period's sample time.
   This should have very good absolute accuracy in anything using NTP, which
   is the default for Linux distros for years now.*

           We are using that timestamp - frame_count - although it's in
sample numbers rather than seconds.Or are you refering to the
PaStreamCallbackTimeInfo that is also passed to the callback?


Jake

**Comment by xyzzy42** [comment]
The native rate is different for different hardware.  Sometimes there is just one rate, other times there are multiple rates.  Most common now is 48,000 samples/sec.  

`frame_count` only provides the number of samples in the buffer.  The timestamp is PaStreamCallbackTimeInfo.

**Pull request closed without merging**
